name: Pull and Commit Traffic Data

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes UTC
  workflow_dispatch:        # optional manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python pool-data-from-server_HAC_cron_job.py

    - name: Commit and push updated CSV files
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data/*.csv
        git commit -m "Update traffic CSVs [automated]" || echo "No changes to commit"
        git push
